#! /usr/bin/bash

echo "building purgo for the following platforms: windows, linux and darwin"

if [ ! -d "bin" ]; then
  mkdir bin
fi

CGO_ENABLED=0 GOOS=windows go build -o bin/purgo.exe -ldflags='-w -s' cmd/main.go
CGO_ENABLED=0 GOOS=linux go build -o bin/purgo -ldflags='-w -s' cmd/main.go
CGO_ENABLED=0 GOOS=darwin go build -o bin/purgo-darwin -ldflags='-w -s' cmd/main.go

echo "finished, look in the bin/ folder"
